### PR TITLE
Move gpio setup/cleanup out of loop.

### PR DESCRIPTION
**Pull request by mangesh-pardeshi**
Repeated setup/cleanup done in the main for loop sometimes make the sensor get into bad state.

### CODE REVIEW

**Comment by alaudet** [comment]
Hi and thanks for taking the time to issue a pull request.  

Under what conditions does this happen?  I have not run into this at all and I have stress tested this script under different scenarios running large samples and fast reading samples.  I would like to know more on this issue so I can try and replicate it.

Allthough it does make sense to only assign and cleanup the pins once rather than each iteration.

**Comment by mangesh-pardeshi** [comment]
No problem Al. I experienced it on Raspberry Pi zero. The loop executes fine the first time but subsequent iterations get missed since the echo pin status is undefined (my educated guess). At that point, the only way to recover is to power cycle the sensor.
Moving the setup/cleanup out of the loop works flawlessly for me.

**Comment by alaudet** [comment]
Ok thanks.  I will take a look at it.

**Comment by alaudet** [comment]
Everything tested fine.  I have merged it into devel branch as I am working on a few other things ahead of the next release.  Your changes will be in the next release.  Thanks for contributing.  Cheers.

**Comment by mangesh-pardeshi** [comment]
Thank you!

**Pull request closed without merging**
