### PR TITLE
Optimize the time-point recording

### PR DESCRIPTION
**Pull request by mr-ping**
CUP computing is less expensive then memory writing for a computer.

### CODE REVIEW

**Comment by alaudet** [comment]
Can you provide a real example of how this change is beneficial?  I have ran simulations on thousands of readings in short amounts of time and have not noticed any performance issues at all.  Is this just a design preference or is it solving a problem you are having with the sensor in a specific situation.

**Comment by mr-ping** [comment]
It's just a performance optimizing I think. The memory writing is IO operations. CPU computing is always faster then IO. is not it?

**Comment by alaudet** [comment]
I will stress test the original code compared to your submission.  If there is an improvement and it works fine I will merge it.  Ultimately if there is no difference I would be inclined not to merge the change as it seems to be working fine right now.
I hope to have a chance to look at it this week.

**Comment by alaudet** [comment]
I have stress tested the changes extensively on very high samples at different speeds and see no difference at all in CPU usage.  Speed of readings are also identical.  Without better understanding the impact of the change I am not going to merge this.  

I am willing to reconsider if I can see what the difference is or a real world example that improves things, your code passes all tests and everything works fine.  The only difference is that CPU usage seems to fluctuate a little more with these changes and is more steady with the existing code.  It still uses so little resources though (from 1% to 5 % depending on sample_size and sample_wait passed to raw_distance().  And this is on taking 10, 50, 100 continuous readings which is far above what anyone would use in the real world.

I do however want to thank you for submitting this as I have still learned from it, I just can't see what benefit it provides in this case though.  

If there had been a noticeable improvement in CPU usage, mem usage of speed that the readings happened I would have been happy to merge, but I don't see the difference and the current library is working fine.

**Pull request closed without merging**
